#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFM.Common
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="NGCP0100")]
	public partial class AuthDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 拡張メソッドの定義
    partial void OnCreated();
    partial void InserttblUser(tblUser instance);
    partial void UpdatetblUser(tblUser instance);
    partial void DeletetblUser(tblUser instance);
    #endregion
		
		public AuthDBDataContext() :
        base(global::System.Configuration.ConfigurationManager.ConnectionStrings["AuthDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AuthDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AuthDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AuthDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AuthDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblUser> tblUser
		{
			get
			{
				return this.GetTable<tblUser>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetSingleUser")]
		public ISingleResult<GetSingleUserResult> GetSingleUser([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IN_iUserID", DbType="Int")] System.Nullable<int> iN_iUserID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iN_iUserID);
			return ((ISingleResult<GetSingleUserResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ValidateUserLogin")]
		public ISingleResult<ValidateUserLoginResult> ValidateUserLogin([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IN_vEmail", DbType="NVarChar(50)")] string iN_vEmail, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IN_vPassword", DbType="NVarChar(10)")] string iN_vPassword)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iN_vEmail, iN_vPassword);
			return ((ISingleResult<ValidateUserLoginResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblUser")]
	public partial class tblUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _iUserID;
		
		private string _vName;
		
		private string _vEmail;
		
		private string _vPassword;
		
		private short _iAccess;
		
		private System.Nullable<System.DateTime> _dtLastLogin;
		
		private string _vMemo;
		
		private System.DateTime _createdDate;
		
		private string _createdUser;
		
		private System.DateTime _updatedDate;
		
		private string _updatedUser;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OniUserIDChanging(int value);
    partial void OniUserIDChanged();
    partial void OnvNameChanging(string value);
    partial void OnvNameChanged();
    partial void OnvEmailChanging(string value);
    partial void OnvEmailChanged();
    partial void OnvPasswordChanging(string value);
    partial void OnvPasswordChanged();
    partial void OniAccessChanging(short value);
    partial void OniAccessChanged();
    partial void OndtLastLoginChanging(System.Nullable<System.DateTime> value);
    partial void OndtLastLoginChanged();
    partial void OnvMemoChanging(string value);
    partial void OnvMemoChanged();
    partial void OncreatedDateChanging(System.DateTime value);
    partial void OncreatedDateChanged();
    partial void OncreatedUserChanging(string value);
    partial void OncreatedUserChanged();
    partial void OnupdatedDateChanging(System.DateTime value);
    partial void OnupdatedDateChanged();
    partial void OnupdatedUserChanging(string value);
    partial void OnupdatedUserChanged();
    #endregion
		
		public tblUser()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iUserID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int iUserID
		{
			get
			{
				return this._iUserID;
			}
			set
			{
				if ((this._iUserID != value))
				{
					this.OniUserIDChanging(value);
					this.SendPropertyChanging();
					this._iUserID = value;
					this.SendPropertyChanged("iUserID");
					this.OniUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vName", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string vName
		{
			get
			{
				return this._vName;
			}
			set
			{
				if ((this._vName != value))
				{
					this.OnvNameChanging(value);
					this.SendPropertyChanging();
					this._vName = value;
					this.SendPropertyChanged("vName");
					this.OnvNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vEmail", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string vEmail
		{
			get
			{
				return this._vEmail;
			}
			set
			{
				if ((this._vEmail != value))
				{
					this.OnvEmailChanging(value);
					this.SendPropertyChanging();
					this._vEmail = value;
					this.SendPropertyChanged("vEmail");
					this.OnvEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vPassword", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string vPassword
		{
			get
			{
				return this._vPassword;
			}
			set
			{
				if ((this._vPassword != value))
				{
					this.OnvPasswordChanging(value);
					this.SendPropertyChanging();
					this._vPassword = value;
					this.SendPropertyChanged("vPassword");
					this.OnvPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iAccess", DbType="SmallInt NOT NULL")]
		public short iAccess
		{
			get
			{
				return this._iAccess;
			}
			set
			{
				if ((this._iAccess != value))
				{
					this.OniAccessChanging(value);
					this.SendPropertyChanging();
					this._iAccess = value;
					this.SendPropertyChanged("iAccess");
					this.OniAccessChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtLastLogin", DbType="DateTime")]
		public System.Nullable<System.DateTime> dtLastLogin
		{
			get
			{
				return this._dtLastLogin;
			}
			set
			{
				if ((this._dtLastLogin != value))
				{
					this.OndtLastLoginChanging(value);
					this.SendPropertyChanging();
					this._dtLastLogin = value;
					this.SendPropertyChanged("dtLastLogin");
					this.OndtLastLoginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vMemo", DbType="NVarChar(255)")]
		public string vMemo
		{
			get
			{
				return this._vMemo;
			}
			set
			{
				if ((this._vMemo != value))
				{
					this.OnvMemoChanging(value);
					this.SendPropertyChanging();
					this._vMemo = value;
					this.SendPropertyChanged("vMemo");
					this.OnvMemoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdDate", DbType="DateTime NOT NULL")]
		public System.DateTime createdDate
		{
			get
			{
				return this._createdDate;
			}
			set
			{
				if ((this._createdDate != value))
				{
					this.OncreatedDateChanging(value);
					this.SendPropertyChanging();
					this._createdDate = value;
					this.SendPropertyChanged("createdDate");
					this.OncreatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdUser", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string createdUser
		{
			get
			{
				return this._createdUser;
			}
			set
			{
				if ((this._createdUser != value))
				{
					this.OncreatedUserChanging(value);
					this.SendPropertyChanging();
					this._createdUser = value;
					this.SendPropertyChanged("createdUser");
					this.OncreatedUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updatedDate", DbType="DateTime NOT NULL")]
		public System.DateTime updatedDate
		{
			get
			{
				return this._updatedDate;
			}
			set
			{
				if ((this._updatedDate != value))
				{
					this.OnupdatedDateChanging(value);
					this.SendPropertyChanging();
					this._updatedDate = value;
					this.SendPropertyChanged("updatedDate");
					this.OnupdatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updatedUser", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string updatedUser
		{
			get
			{
				return this._updatedUser;
			}
			set
			{
				if ((this._updatedUser != value))
				{
					this.OnupdatedUserChanging(value);
					this.SendPropertyChanging();
					this._updatedUser = value;
					this.SendPropertyChanged("updatedUser");
					this.OnupdatedUserChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class GetSingleUserResult
	{
		
		private int _iUserID;
		
		private string _vName;
		
		private string _vEmail;
		
		private string _vPassword;
		
		private short _iAccess;
		
		private System.Nullable<System.DateTime> _dtLastLogin;
		
		private string _vMemo;
		
		private System.DateTime _createdDate;
		
		private string _createdUser;
		
		private System.DateTime _updatedDate;
		
		private string _updatedUser;
		
		public GetSingleUserResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iUserID", DbType="Int NOT NULL")]
		public int iUserID
		{
			get
			{
				return this._iUserID;
			}
			set
			{
				if ((this._iUserID != value))
				{
					this._iUserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vName", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string vName
		{
			get
			{
				return this._vName;
			}
			set
			{
				if ((this._vName != value))
				{
					this._vName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vEmail", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string vEmail
		{
			get
			{
				return this._vEmail;
			}
			set
			{
				if ((this._vEmail != value))
				{
					this._vEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vPassword", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string vPassword
		{
			get
			{
				return this._vPassword;
			}
			set
			{
				if ((this._vPassword != value))
				{
					this._vPassword = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iAccess", DbType="SmallInt NOT NULL")]
		public short iAccess
		{
			get
			{
				return this._iAccess;
			}
			set
			{
				if ((this._iAccess != value))
				{
					this._iAccess = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtLastLogin", DbType="DateTime")]
		public System.Nullable<System.DateTime> dtLastLogin
		{
			get
			{
				return this._dtLastLogin;
			}
			set
			{
				if ((this._dtLastLogin != value))
				{
					this._dtLastLogin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vMemo", DbType="NVarChar(255)")]
		public string vMemo
		{
			get
			{
				return this._vMemo;
			}
			set
			{
				if ((this._vMemo != value))
				{
					this._vMemo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdDate", DbType="DateTime NOT NULL")]
		public System.DateTime createdDate
		{
			get
			{
				return this._createdDate;
			}
			set
			{
				if ((this._createdDate != value))
				{
					this._createdDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdUser", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string createdUser
		{
			get
			{
				return this._createdUser;
			}
			set
			{
				if ((this._createdUser != value))
				{
					this._createdUser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updatedDate", DbType="DateTime NOT NULL")]
		public System.DateTime updatedDate
		{
			get
			{
				return this._updatedDate;
			}
			set
			{
				if ((this._updatedDate != value))
				{
					this._updatedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updatedUser", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string updatedUser
		{
			get
			{
				return this._updatedUser;
			}
			set
			{
				if ((this._updatedUser != value))
				{
					this._updatedUser = value;
				}
			}
		}
	}
	
	public partial class ValidateUserLoginResult
	{
		
		private int _iUserID;
		
		private string _vName;
		
		private string _vEmail;
		
		private string _vPassword;
		
		private short _iAccess;
		
		private System.Nullable<System.DateTime> _dtLastLogin;
		
		private string _vMemo;
		
		private System.DateTime _createdDate;
		
		private string _createdUser;
		
		private System.DateTime _updatedDate;
		
		private string _updatedUser;
		
		public ValidateUserLoginResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iUserID", DbType="Int NOT NULL")]
		public int iUserID
		{
			get
			{
				return this._iUserID;
			}
			set
			{
				if ((this._iUserID != value))
				{
					this._iUserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vName", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string vName
		{
			get
			{
				return this._vName;
			}
			set
			{
				if ((this._vName != value))
				{
					this._vName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vEmail", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string vEmail
		{
			get
			{
				return this._vEmail;
			}
			set
			{
				if ((this._vEmail != value))
				{
					this._vEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vPassword", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string vPassword
		{
			get
			{
				return this._vPassword;
			}
			set
			{
				if ((this._vPassword != value))
				{
					this._vPassword = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iAccess", DbType="SmallInt NOT NULL")]
		public short iAccess
		{
			get
			{
				return this._iAccess;
			}
			set
			{
				if ((this._iAccess != value))
				{
					this._iAccess = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtLastLogin", DbType="DateTime")]
		public System.Nullable<System.DateTime> dtLastLogin
		{
			get
			{
				return this._dtLastLogin;
			}
			set
			{
				if ((this._dtLastLogin != value))
				{
					this._dtLastLogin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vMemo", DbType="NVarChar(255)")]
		public string vMemo
		{
			get
			{
				return this._vMemo;
			}
			set
			{
				if ((this._vMemo != value))
				{
					this._vMemo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdDate", DbType="DateTime NOT NULL")]
		public System.DateTime createdDate
		{
			get
			{
				return this._createdDate;
			}
			set
			{
				if ((this._createdDate != value))
				{
					this._createdDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdUser", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string createdUser
		{
			get
			{
				return this._createdUser;
			}
			set
			{
				if ((this._createdUser != value))
				{
					this._createdUser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updatedDate", DbType="DateTime NOT NULL")]
		public System.DateTime updatedDate
		{
			get
			{
				return this._updatedDate;
			}
			set
			{
				if ((this._updatedDate != value))
				{
					this._updatedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updatedUser", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string updatedUser
		{
			get
			{
				return this._updatedUser;
			}
			set
			{
				if ((this._updatedUser != value))
				{
					this._updatedUser = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
